title: City of Vernonia Geospatial Data

description: City of Vernonia geospatial data.

permalink: pretty

defaults:
  - scope:
      path: ''
    values:
      layout: default

exclude:
  - README.md
  - scripts
  - Gemfile
  - node_modules
  - package.json
  - package-lock.json
  - prettier.config.js
  - .gitignore
