name: Deploy Geospatial Data
on:
  push:
    branches:
      - main
    paths:
      - packages/geospatial-data

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: packages/geospatial-data
    steps:
      - uses: actions/checkout@v4
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          enable_jekyll: true
          disable_nojekyll: true
          publish_dir: ./packages/geospatial-data
